name: 02 - Workflow Events

on: 
    push:
    pull_request:

jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: 
                "Triggered by event : ${{ github.event_name }}"
    
