name: 02 - Workflow Events

on: 
    pull_request:
    workflow_dispatch:

jobs: 
    echojob:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Triggered by event :${{ github.event_name }}"
    
